name: tf2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip==23.3.1
  - keras
  - matplotlib
  - scikit-learn
  - scikit-image
  - ipykernel
  - opencv
  # - cudatoolkit
  - nbdime
  - black
  - pip:
    - tensorflow-cpu==2.14.0